@api = http://localhost:3000/products



GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "latitud" : "nazi",
    "longitud" : "-nazi"
   

}

###
GET {{api}}/5

###
DELETE  {{api}}/4


###
GET {{api}}/count

###
PUT {{api}}/6
Content-Type: application/json

{
    "name": "Hood remix",
    "description" : "trueno",
    "quantity" : 12
}
